/* 
 * Revenium Metering API
 *
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.io.revenium;
using IO.Swagger.io.revenium;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MeteringRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MeteringRequestDTOTests
    {
        // TODO uncomment below to declare an instance variable for MeteringRequestDTO
        //private MeteringRequestDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MeteringRequestDTO
            //instance = new MeteringRequestDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MeteringRequestDTO
        /// </summary>
        [Test]
        public void MeteringRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MeteringRequestDTO
            //Assert.IsInstanceOfType<MeteringRequestDTO> (instance, "variable 'instance' is a MeteringRequestDTO");
        }


        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Test]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }
        /// <summary>
        /// Test the property 'ProductKey'
        /// </summary>
        [Test]
        public void ProductKeyTest()
        {
            // TODO unit test for the property 'ProductKey'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Test]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'BackendLatency'
        /// </summary>
        [Test]
        public void BackendLatencyTest()
        {
            // TODO unit test for the property 'BackendLatency'
        }
        /// <summary>
        /// Test the property 'GatewayLatency'
        /// </summary>
        [Test]
        public void GatewayLatencyTest()
        {
            // TODO unit test for the property 'GatewayLatency'
        }
        /// <summary>
        /// Test the property 'ResponseCode'
        /// </summary>
        [Test]
        public void ResponseCodeTest()
        {
            // TODO unit test for the property 'ResponseCode'
        }
        /// <summary>
        /// Test the property 'TimedOut'
        /// </summary>
        [Test]
        public void TimedOutTest()
        {
            // TODO unit test for the property 'TimedOut'
        }
        /// <summary>
        /// Test the property 'RequestMessageSize'
        /// </summary>
        [Test]
        public void RequestMessageSizeTest()
        {
            // TODO unit test for the property 'RequestMessageSize'
        }
        /// <summary>
        /// Test the property 'ResponseMessageSize'
        /// </summary>
        [Test]
        public void ResponseMessageSizeTest()
        {
            // TODO unit test for the property 'ResponseMessageSize'
        }
        /// <summary>
        /// Test the property 'RequestHeaders'
        /// </summary>
        [Test]
        public void RequestHeadersTest()
        {
            // TODO unit test for the property 'RequestHeaders'
        }
        /// <summary>
        /// Test the property 'ResponseHeaders'
        /// </summary>
        [Test]
        public void ResponseHeadersTest()
        {
            // TODO unit test for the property 'ResponseHeaders'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Test]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'RemoteUser'
        /// </summary>
        [Test]
        public void RemoteUserTest()
        {
            // TODO unit test for the property 'RemoteUser'
        }
        /// <summary>
        /// Test the property 'RemoteHost'
        /// </summary>
        [Test]
        public void RemoteHostTest()
        {
            // TODO unit test for the property 'RemoteHost'
        }
        /// <summary>
        /// Test the property 'HttpProtocol'
        /// </summary>
        [Test]
        public void HttpProtocolTest()
        {
            // TODO unit test for the property 'HttpProtocol'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Test]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'PlatformAPIKey'
        /// </summary>
        [Test]
        public void PlatformAPIKeyTest()
        {
            // TODO unit test for the property 'PlatformAPIKey'
        }
        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Test]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
