/*
 * Revenium Metering API
 *
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Revenium.Metering.Attributes;
using IO.Revenium.Metering.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Revenium.Metering.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventsApiController : ControllerBase
    { 
        /// <summary>
        /// Save can API event
        /// </summary>
        /// <remarks>Save an API event</remarks>
        /// <param name="body"></param>
        /// <response code="201">Metering data successfully recorded</response>
        [HttpPost]
        [Route("/meter/v1/api/event")]
        [ValidateModelState]
        [SwaggerOperation("SaveEvent")]
        public virtual IActionResult SaveEvent([FromBody]ApiEventDTO body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(201);

            throw new NotImplementedException();
        }
    }
}
